// Generated by https://quicktype.io
//generado con shift+command+p y Paste JSON as Code

export interface DashboardSummaryResponse {
    numberOfOrders:          number;
    paidOrders:              number;
    numberOfClients:         number;
    numberOfProducts:        number;
    productsWithNoInventory: number;
    lowInventory:            number;
    notPaidOrders:           number;
}
